config/routes.rb
Rails.application.routes.draw do
  resources :pets
  resources :articles, only: [:show, :index]
  root 'pages#home'
  get 'about', to: 'pages#about'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true, length: {minimum: 6, maximum: 100}
  validates :description, presence: true, length: {minimum: 10}
end

app/models/pet.rb
class Pet < ApplicationRecord
  validates :Breed, length: {minimum: 3}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def show
    @article = Article.find(params[:id])
  end

  def index
    @articles = Article.all
  end
end

app/controllers/lloyd_controller.rb
class LloydController < ApplicationController
  def lloyd

  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home

  end

  def about

  end


end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  before_action :set_pet, only: %i[ show edit update destroy ]

  # GET /pets or /pets.json
  def index
    @pets = Pet.all
  end

  # GET /pets/1 or /pets/1.json
  def show
  end

  # GET /pets/new
  def new
    @pet = Pet.new
  end

  # GET /pets/1/edit
  def edit
  end

  # POST /pets or /pets.json
  def create
    @pet = Pet.new(pet_params)

    respond_to do |format|
      if @pet.save
        format.html { redirect_to pet_url(@pet), notice: "Pet was successfully created." }
        format.json { render :show, status: :created, location: @pet }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pets/1 or /pets/1.json
  def update
    respond_to do |format|
      if @pet.update(pet_params)
        format.html { redirect_to pet_url(@pet), notice: "Pet was successfully updated." }
        format.json { render :show, status: :ok, location: @pet }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pets/1 or /pets/1.json
  def destroy
    @pet.destroy

    respond_to do |format|
      format.html { redirect_to pets_url, notice: "Pet was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pet
      @pet = Pet.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def pet_params
      params.require(:pet).permit(:Name, :History)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/lloyd_helper.rb
module LloydHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/views/articles/_article.html.erb
<div id="<%= dom_id article %>">
  <p>
    <strong>Title:</strong>
    <%= article.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= article.description %>
  </p>

</div>

app/views/articles/_form.html.erb
<%= form_with(model: article) do |form| %>
  <% if article.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
        <% article.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render "form", article: @article %>

<br>

<div>
  <%= link_to "Show this article", @article %> |
  <%= link_to "Back to articles", articles_path %>
</div>

app/views/articles/index.html.erb
<h1>Articles listing page</h1>
<form action="http://localhost:3000/">
  <input type="submit" value="home"/>
</form>
<table>
  <thead>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th>Actions</th>
  </tr>
  </thead>
  <tbody>
  <% @articles.each do |article| %>
    <tr>
      <td><%= article.title %></td>
      <td><%= article.description %></td>

    </tr>
  <% end %>
  </tbody>
</table>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= render "form", article: @article %>

<br>

<div>
  <%= link_to "Back to articles", articles_path %>
</div>

app/views/articles/show.html.erb
<h1> Showing articles details</h1>
<p><strong>Title: </strong>
  <%= @article.title %></p>
<p><strong>Description: </strong>
  <%= @article.description %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestAppRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lloyd/lloyd.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <link rel = "stylesheet" href="mycss.css">
  <meta charset="utf-8">
  <title>Pintacats</title>
</head>
<body>
<h1>The PintaCats</h1>
<p>Welcome to the pintacats family.</p>
<div class="awesome">...</div>
<p class="awesome">...</p>

<p id="food">This is food</p>
<ul>
  <li>Tiger</li>
  <li>Panther</li>
  <li>Snow</li>
  <li>Storm</li>
  <li>Insert Pet here</li>
</ul>
</body>
</html>

app/views/pages/about.html.erb
<form action="http://localhost:3000/">
  <input type="submit" value="Home" />
</form>

<h1>List of Pintacats</h1>
<ul>
  <li>Tiger</li>
  <li>Panther</li>
  <li>Snow</li>
  <li>Storm</li>
</ul>

app/views/pages/home.html.erb
<h1>Welcome to Pintacats</h1>

<form action="http://localhost:3000/about">
  <input type="submit" value="List of Pintacats" />
</form>
<form action="http://localhost:3000/articles">
  <input type="submit" value="List of Articles"/>
</form>
<form action="http://localhost:3000/pets">
  <input type="submit" value="List of Pets"/>
</form>



<!--<form action="https://lloyd-pintac.herokuapp.com/pets">-->
<!--  <input type="submit" value="Add Pets" />-->
<!--</form>-->
Testing By: Lloyd Pintac

app/views/pets/_form.html.erb
<%= form_with(model: pet) do |form| %>
  <% if pet.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(pet.errors.count, "error") %> prohibited this pet from being saved:</h2>

      <ul>
        <% pet.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :Name, style: "display: block" %>
    <%= form.text_field :Name %>
  </div>

  <div>
    <%= form.label :History, style: "display: block" %>
    <%= form.text_area :History %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/pets/_pet.html.erb
<div id="<%= dom_id pet %>">
  <p>
    <strong>Name:</strong>
    <%= pet.Name %>
  </p>

  <p>
    <strong>History:</strong>
    <%= pet.History %>
  </p>

</div>

app/views/pets/edit.html.erb
<h1>Editing pet</h1>

<%= render "form", pet: @pet %>

<br>

<div>
  <%= link_to "Show thisss #{@pet}", @pet %> |
  <%= link_to "Back to pets", pets_path %>
</div>

app/views/pets/index.html.erb
<p style="color: green"><%= notice %></p>
<form action="http://localhost:3000/">
  <input type="submit" value="Home"/>
</form>
<h1>Pets</h1>

<div id="pets">
  <% @pets.each do |pet| %>
    <%= render pet %>
    <p>
      <%= link_to "Show this pet", pet %>
    </p>
  <% end %>
</div>

<%= link_to "New pet", new_pet_path %>

app/views/pets/new.html.erb
<h1>New pet</h1>

<%= render "form", pet: @pet %>

<br>

<div>
  <%= link_to "Back to pets", pets_path %>
</div>

app/views/pets/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @pet %>

<div>
  <%= link_to "Edit this pet", edit_pet_path(@pet) %> |
  <%= link_to "Back to pets", pets_path %>

  <%= button_to "Destroy this pet", @pet, method: :delete %>
</div>